// ignore_for_file: equal_keys_in_map

import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'tm': {
          "workers": "Işgärler",
          //
          "addBrend": "Brend goş",
          "addCategory": "Kategoriya goş",
          "addLocation": "Salgy goş",
          "addMaterial": "Material goş",
          "name": "Ady",
          'created': 'Döredildi',
          'edited': 'Üýtgedildi',
          'deleted': 'Pozuldy',
          'logs': 'Log ýazgylary',
          "addData": "Maglumat goş",
          'client_name': 'Ulanyjy ady',
          "add_client": "Ulanyjy goş",
          "success": "Tassyklandy",
          "clientAdded": "Ulanyjy üstünlikli goşuldy",
          "clientNotAdded": "Maglumatlary barlaň we gaýtadan synanyşyň",
          "deleted": "Pozuldy",
          "clientDeleted": "Ulanyjy pozuldy",
          "clientName": "Ulanyjy ady",
          "phone": "Telefon belgisi",
          "gaplama": "Gaplama",
          "coupon": "Koupone",
          "count": "Haryt sany",
          "totalsum": "Harytlary üçin çykdaýjy ",
          "totalchykdajy": "Satylan bahasy",
          "admin": "Admin",
          "users": "Ulanyjylar",
          "clients": "Müşderiler",
          "expences": "Çykdaýjylar",
          "purchases": "Satyn almalar",
          "orderCount": "Sargyt sany",
          "sumPrice": "Jemi söwda",
          "places": "Dükanlarymyz",
          "expences_name": "Çykdaýjy ady",
          "cost": "Jemi çykdaýjy",
          "sellPrice": "Satylýan bahasy",
          "costPrice": "Satyn alynan bahasy",
          "inStock": "Elimizde bar",
          "salesChart": "Satylan harytlar",
          "sumCostChart": "Haryt çykdaýjylary",
          "netProfit": "Jemi gazanç",
          "orderName": "Sargyt ady",
          "shipped": "Eltildi",
          "canceled": "Ýatyryldy",
          "refund": "Yzyna gaýtaryldy",
          "preparing": "Taýýarlanýar",
          "readyToShip": "Eltmäge taýýar",
          "clearFilter": "Arassala",
          'select_language': 'Dil saýlaň',
          'selectMoreProducts': 'Bir ýa-da birnäçe önümi saýlamagyňyzy haýyş edýäris',
          'done': "Soňy",
          'sumCost': "Jemi çykdaýjy",
          'cannotChangeOrderStatus': "Sargyt ýagdaýyny üýtgedip bilmersiňiz",
          "notHigherThanSumPrice": "Arzanladyş bahasy Jemi bahasyndan ýokary bolup bilmez",
          "createOrder": "Sargyt döretmek",
          'selectProducts': 'Harytlar saýlaň',
          'selectedProducts': 'Saýlanan harytlar',
          'dateOrder': 'Sargyt senesi:',
          'sales': "Sargytlar",
          'errorDontChangeData': "Siz hiç zat üýtgetmediňiz",
          'selectedImage': "Saýlanan surat",
          'totalProducts': 'Hemme harytlar',
          'stockInHand': 'Elimizdaki harytlar',
          'endOFProduct': 'Başga haryt ýok',
          'noProduct': "Harytlar tapylmady",
          'aboutUs': 'Biz barada',
          'add': 'Goş',
          'addAddress': 'Salgy goş',
          'addCart': 'Sebede goş',
          'added': 'Goşuldy',
          'addedSubtitle': 'Sebede haryt goşuldy ',
          'address': 'Öý salgyňyz',
          'agree': 'Tassyklamak',
          'alreadyExist': 'Ulanyjy maglumatlaryňyz bizde ýok. Hasaba al bölümden hasaba girmegiňizi haýýyş edýäris',
          'appColor': 'Programma reňki',
          'appColor1': 'Reňk saýlaň',
          'appColor2': 'Reňk 1',
          'appColor3': 'Reňk 2',
          'appColor4': 'Reňk 3',
          'appObtained': 'Hasap açmak isleseňiz, bu programmany alan adamyňyza ýüz tutmagyňyzy haýyş edýäris',
          'balance': 'Hasap',
          'banner': 'Reklama',
          'brand': 'Brand',
          'brandPP': 'Brand',
          'brands': 'Brendler',
          'call': 'Jaň et',
          'callNumber': 'Telefon Belgilerimiz',
          'cart': 'Sebet',
          'cartEmpty': 'Sebediňiz boş',
          'cartEmptySubtitle': 'Sebediňize hiç zat goşmadyňyz.',
          'cash': 'Nagt',
          'cashSubtitle': 'Sargydy alan wagtyňyz nagt görnüşde hasaplaşmak',
          'categoriesMini': 'Kategoriýalar',
          'category': 'Kategoriýa',
          'changesUpdated': 'Maglumatlar üýtgedildi',
          'chooseTheColor': 'Renk saýlaň : ',
          'chooseTheSize': 'Razmer :',
          'clientAddress': 'Ulanyjy salgysy',
          'clientNumber': 'Belgisi',
          'clientNumber': 'Telefon belgisi',
          'come': 'Geldi',
          'contactInformation': 'Habarlaşmak üçin : ',
          'container': 'Kontainer',
          'copySucces': 'Tassyklandy',
          'copySuccesSubtitle': 'Göçürme ýerine ýetirildi',
          'countProducts': 'Harytlar : ',
          'creatOrder': 'Sargyt döretmek',
          'date': 'Sene : ',
          'description': 'Düşündiriş',
          'discount': 'Arzanladyş',
          'download': 'Ýükle',
          'downloaded': 'Ýüklänlerim',
          'downloadFiles': 'Ýüklemek',
          'doYouWantToDeleteCart': 'Sebedi boşat !',
          'doYouWantToDeleteCartSubtitle': 'Siz hakykatdanam Sebedi boşatmakçymy ?',
          'emptyCart': 'Sebet boş',
          'error': 'Ýalňyşlyk ýüze çykdy täzeden synanşyň',
          'errorData': 'Girizeň maglumatyňyz ýalňyş !',
          'errorEmpty': 'Tekst gutusy boş bolup bilmez',
          'errorPassword': 'Parol azyndan 6 haryp bolmaly',
          'errorPassword2': 'Parolyňyz ýalňyş',
          'errorPhoneCount': 'Telefon belgiňiz 8 sanly bolmaly.',
          'errorTitle': 'Ýalňyş',
          'favorites': 'Halanlarym',
          'filter': 'Filter',
          'fixMachine': 'Bejeriş Hyzmaty',
          'giveLike': 'Bizi Play marketde bahalandyryň',
          'gramm': 'Gram',
          'hastags': 'Haştaglar',
          'home': 'Baş sahypa',
          'inOurHands': 'Şulary hem halap bilersiňiz',
          'kargoIncluded': 'Kargo mugt',
          'location': 'Haryt salgysy',
          'locations': 'Salgylarym',
          'log_out_title': 'Siz hakykatdanda ulgamdan çykmak isleýärsiňizmi ?',
          'log_out': 'Ulgamdan çyk',
          'login': 'Ulgama gir',
          'loginSubtitle': 'Ulgama girmek üçin ulanyjy maglumatlary doly we dogry şekilde dolduryň',
          'loginErrorFillBlanks': 'Boş ýerleri doldurmagyňyzy haýyş edýäris',
          'loginError': 'Ulgama giriň',
          'loginError1': 'Kimdir biri bu giriş maglumatlaryny ulanýar',
          'loginErrorSubtitle': 'Sargyt etmek üçin ulgama giriň',
          'loginErrorSubtitle1': 'Hyzmaty ýerine etmek üçin ulgama giriň',
          'material': 'Materialy',
          'maxPrice': 'Iň gymmat',
          'minPrice': 'Iň arzan',
          'minSumCount': 'Sargydyňyzyň jemi azyndan 50 manat bolmaly',
          'more': 'Goşmaçalar',
          'no': 'Ýok',
          'noConnection1': 'Aragatnaşyk ýok',
          'noConnection2': 'Internede baglanyp bolmady.Internet sazlamalaryňyzy barlap gaýtadan synanşyň !',
          'noConnection3': 'Täzeden synanş',
          'noData': 'Maglumat ýüklenmedi, täzeden synanşyň',
          'noData1': 'Wagtlaýynça maglumat ýok !',
          'noFile': 'Hiç hili Faýl ýok. Biz bilen habarlaşyň',
          'noHistoryOrders': 'Hiç hili sargyt etmediňiz',
          'noImage': 'Surat ýok',
          'noMoney': 'Pul ýok',
          'noMoneySubtitle': 'Hyzmaty ýerine ýetirmek üçin Puluňyz ýetenok',
          'noProductTitle': 'Gutardy',
          'note': 'Bellik',
          'notification': 'Bildirişler',
          'notWork': 'Işlänok',
          'notWorkSubtitle': 'Waglaýynça hyzmat işlänok',
          'order_status_come': 'Gelenler',
          'order_status_submission': 'Tabşyrylanlar',
          'order_status_wait': 'Sargyt edilenler',
          'order': 'Sargyt',
          'orders': 'Sargytlarym',
          'ordersDeleted': 'Salgylaryňyz pozuldy ',
          'orderSubtitle': 'Sargydyňyz ýerine ýetirmek üçin nobata goýuldy',
          'orderType': 'Sargyt görnüşi',
          'otp': 'Sms kod',
          'otpCheck': 'Otp Werfikasiýa',
          'otpErrorSubtitle': 'Sms koduňyzy ýene bir gezek barlaň',
          'otpErrorTitle': 'SMS kod ýalňyşlygy',
          'otpSubtitle': 'Telefon belgiňize gelen sms kody giriziň',
          'otpTitle': 'Ýazan belgiňize sms arkaly kod ugradylar.',
          'ourDeliveryService': 'Eltip bermek we töleg',
          'package': 'Gaplama',
          'paymentMethod': 'Töleg görnüşi',
          'phoneNumber': 'Telefon belgiňiz',
          'plain': 'Uçar',
          'price': 'Bahasy :',
          'priceProduct': 'Jemi Bahasy : ',
          'priceRange': 'Baha aralygy',
          'product': 'Haryt',
          'productAddToFav': 'Haryt halanlarym goşuldy',
          'productCount': 'Haryt sany',
          'productName': 'Haryt ady',
          'products': 'Harytlar',
          'profil': 'Ulanyjy',
          'quantity': 'Sany',
          'questions': 'Köp soralýan soraglar ?',
          'read': 'Oka',
          'referal_Code': 'Referal Kod',
          'referalDesc': 'Bu kod Üsti bilen ulanyjylary çagyryp bilersiňiz ve Pul gazanyp bilersiňiz',
          'referalKod': 'Referal kod',
          'referalKod1': 'Referal kodyňyz',
          'referalKodEarnedMoney': 'Jemi gazanç :',
          'referalKodUsedUser': 'Kody ulanan ulanyjylar',
          'search': 'Gözleg',
          'settings': 'Sazlamalar',
          'signInDialog': 'Ulgama girmek üçin ulanyjy maglumatlary doly we dogry şekilde dolduruň',
          'status': 'Ýagdaýy',
          'sum': 'Jemi',
          'uploadImage': 'Surat ýükle',
          'uploadImageProcessDone': 'Surat ýüklendi !',
          'userInfo': 'Ulanyjy maglumatlary :',
          'userName': 'Ulanyjy ady',
          'userpassword': 'Ulanyjy paroly',
          'versia': 'Wersiýa',
          'waiting': 'Garaşylýar',
          'waitMyMan': 'Garaşyň',
          'waitMyManSubtitle': 'Maglumat ýüklenýänça garaşyň',
          'yes': 'Hawwa',
          'totalIncome': "Jemi girdeji",
        },
        'ru': {
          'totalIncome': "Общий доход",
          "addBrend": "Добавить бренд",
          "addCategory": "Добавить категорию",
          "addLocation": "Добавить местоположение",
          "addMaterial": "Добавить материал",
          "name": "Название",
          "created": "Создано",
          "edited": "Отредактировано",
          "deleted": "Удалено",
          "logs": "Логи",
          "addData": "Добавить данные",
          "client_name": "Имя клиента",
          "add_client": "Добавить клиента",
          "success": "Успешно",
          "clientAdded": "Клиент успешно добавлен",
          "clientNotAdded": "Проверьте данные и попробуйте снова",
          "deleted": "Удалено",
          "clientDeleted": "Клиент удалён",
          "clientName": "Имя клиента",
          "phone": "Номер телефона",
          "gaplama": "Упаковка",
          "coupon": "Купон",
          "count": "Количество товара",
          "totalsum": "Расход на товары",
          "totalchykdajy": "Цена продажи",
          "admin": "Админ",
          "users": "Пользователи",
          "clients": "Клиенты",
          "expences": "Расходы",
          "purchases": "Закупки",
          "orderCount": "Количество заказов",
          "sumPrice": "Общая сумма продаж",
          "places": "Наши магазины",
          "expences_name": "Название расхода",
          "cost": "Общие затраты",
          "sellPrice": "Цена продажи",
          "costPrice": "Себестоимость",
          "inStock": "В наличии",
          "salesChart": "Проданные товары",
          "sumCostChart": "Расходы на товары",
          "netProfit": "Чистая прибыль",
          "orderName": "Название заказа",
          "shipped": "Доставлено",
          "canceled": "Отменено",
          "refund": "Возвращено",
          "preparing": "Готовится",
          "readyToShip": "Готово к отправке",
          "clearFilter": "Очистить фильтр",
          "select_language": "Выберите язык",
          "selectMoreProducts": "Пожалуйста, выберите один или несколько товаров",
          "done": "Готово",
          "sumCost": "Общая стоимость",
          "cannotChangeOrderStatus": "Вы не можете изменить статус заказа",
          "notHigherThanSumPrice": "Скидка не может быть выше общей суммы",
          "createOrder": "Создать заказ",
          "selectProducts": "Выберите товары",
          "selectedProducts": "Выбранные товары",
          "dateOrder": "Дата заказа:",
          "sales": "Заказы",
          "errorDontChangeData": "Вы ничего не изменили",
          "selectedImage": "Выбранное изображение",
          "totalProducts": "Все товары",
          "stockInHand": "Товары в наличии",
          "endOFProduct": "Других товаров нет",
          "noProduct": "Товары не найдены",
          "aboutUs": "О нас",
          "add": "Добавить",
          "addAddress": "Добавить адрес",
          "addCart": "Добавить в корзину",
          "added": "Добавлено",
          "addedSubtitle": "Товар добавлен в корзину",
          "address": "Ваш домашний адрес",
          "agree": "Подтвердить",
          "alreadyExist": "Ваших данных у нас нет. Пожалуйста, зарегистрируйтесь в разделе регистрации",
          "appColor": "Цвет приложения",
          "appColor1": "Выберите цвет",
          "appColor2": "Цвет 1",
          "appColor3": "Цвет 2",
          "appColor4": "Цвет 3",
          "appObtained": "Если вы хотите открыть счет, пожалуйста, свяжитесь с человеком, у которого вы приобрели это приложение",
          "balance": "Баланс",
          "banner": "Реклама",
          "brand": "Бренд",
          "brandPP": "Бренд",
          "brands": "Бренды",
          "call": "Позвонить",
          "callNumber": "Наши номера телефонов",
          "cart": "Корзина",
          "cartEmpty": "Ваша корзина пуста",
          "cartEmptySubtitle": "Вы ничего не добавили в корзину.",
          "cash": "Наличные",
          "cashSubtitle": "Оплата наличными при получении заказа",
          "categoriesMini": "Категории",
          "category": "Категория",
          "changesUpdated": "Данные изменены",
          "chooseTheColor": "Выберите цвет : ",
          "chooseTheSize": "Размер :",
          "clientAddress": "Адрес клиента",
          "clientNumber": "Номер телефона",
          "come": "Прибыл",
          "contactInformation": "Для связи : ",
          "container": "Контейнер",
          "copySucces": "Подтверждено",
          "copySuccesSubtitle": "Копирование выполнено",
          "countProducts": "Товары : ",
          "creatOrder": "Создать заказ",
          "date": "Дата : ",
          "description": "Описание",
          "discount": "Скидка",
          "download": "Скачать",
          "downloaded": "Мои загрузки",
          "downloadFiles": "Скачать файлы",
          "doYouWantToDeleteCart": "Очистить корзину!",
          "doYouWantToDeleteCartSubtitle": "Вы действительно хотите очистить корзину?",
          "emptyCart": "Корзина пуста",
          "error": "Произошла ошибка, попробуйте снова",
          "errorData": "Введенные вами данные неверны!",
          "errorEmpty": "Текстовое поле не может быть пустым",
          "errorPassword": "Пароль должен содержать не менее 6 символов",
          "errorPassword2": "Ваш пароль неверный",
          "errorPhoneCount": "Ваш номер телефона должен состоять из 8 цифр.",
          "errorTitle": "Ошибка",
          "favorites": "Избранное",
          "filter": "Фильтр",
          "fixMachine": "Услуги по ремонту",
          "giveLike": "Оцените нас в Play Market",
          "gramm": "Грамм",
          "hastags": "Хештеги",
          "home": "Главная",
          "inOurHands": "Вам также может понравиться",
          "kargoIncluded": "Доставка бесплатно",
          "location": "Адрес товара",
          "locations": "Мои адреса",
          "log_out_title": "Вы действительно хотите выйти из системы?",
          "log_out": "Выйти",
          "login": "Войти",
          "loginSubtitle": "Для входа в систему заполните данные пользователя полностью и правильно",
          "loginErrorFillBlanks": "Пожалуйста, заполните пустые поля",
          "loginError": "Войдите в систему",
          "loginError1": "Кто-то уже использует эти учетные данные",
          "loginErrorSubtitle": "Войдите в систему, чтобы сделать заказ",
          "loginErrorSubtitle1": "Войдите в систему, чтобы выполнить услугу",
          "material": "Материал",
          "maxPrice": "Самый дорогой",
          "minPrice": "Самый дешевый",
          "minSumCount": "Минимальная сумма вашего заказа должна быть 50 манат",
          "more": "Дополнительно",
          "no": "Нет",
          "noConnection1": "Нет соединения",
          "noConnection2": "Не удалось подключиться к интернету. Проверьте настройки интернета и попробуйте снова!",
          "noConnection3": "Попробовать снова",
          "noData": "Данные не загружены, попробуйте снова",
          "noData1": "Временно нет данных!",
          "noFile": "Файлов нет. Свяжитесь с нами",
          "noHistoryOrders": "Вы не делали никаких заказов",
          "noImage": "Нет изображения",
          "noMoney": "Недостаточно средств",
          "noMoneySubtitle": "У вас недостаточно средств для выполнения услуги",
          "noProductTitle": "Закончилось",
          "note": "Примечание",
          "notification": "Уведомления",
          "notWork": "Не работает",
          "notWorkSubtitle": "Услуга временно недоступна",
          "order_status_come": "Прибывшие",
          "order_status_submission": "Переданные",
          "order_status_wait": "Заказанные",
          "order": "Заказ",
          "orders": "Мои заказы",
          "ordersDeleted": "Ваши адреса удалены",
          "orderSubtitle": "Ваш заказ поставлен в очередь на выполнение",
          "orderType": "Тип заказа",
          "otp": "СМС-код",
          "otpCheck": "Проверка OTP",
          "otpErrorSubtitle": "Проверьте ваш СМС-код еще раз",
          "otpErrorTitle": "Ошибка СМС-кода",
          "otpSubtitle": "Введите СМС-код, полученный на ваш номер телефона",
          "otpTitle": "На указанный вами номер был отправлен код по СМС.",
          "ourDeliveryService": "Доставка и оплата",
          "package": "Упаковка",
          "paymentMethod": "Способ оплаты",
          "phoneNumber": "Ваш номер телефона",
          "plain": "Самолет",
          "price": "Цена :",
          "priceProduct": "Общая цена : ",
          "priceRange": "Ценовой диапазон",
          "product": "Товар",
          "productAddToFav": "Товар добавлен в избранное",
          "productCount": "Количество товара",
          "productName": "Название товара",
          "products": "Товары",
          "profil": "Профиль",
          "quantity": "Количество",
          "questions": "Часто задаваемые вопросы ?",
          "read": "Читать",
          "referal_Code": "Реферальный код",
          "referalDesc": "С помощью этого кода вы можете приглашать пользователей и зарабатывать деньги",
          "referalKod": "Реферальный код",
          "referalKod1": "Ваш реферальный код",
          "referalKodEarnedMoney": "Общий заработок :",
          "referalKodUsedUser": "Пользователи, использовавшие код",
          "search": "Поиск",
          "settings": "Настройки",
          "signInDialog": "Для входа в систему заполните данные пользователя полностью и правильно",
          "status": "Статус",
          "sum": "Итого",
          "uploadImage": "Загрузить изображение",
          "uploadImageProcessDone": "Изображение загружено!",
          "userInfo": "Данные пользователя :",
          "userName": "Имя пользователя",
          "userpassword": "Пароль пользователя",
          "versia": "Версия",
          "waiting": "Ожидание",
          "waitMyMan": "Подождите",
          "waitMyManSubtitle": "Подождите, пока загружаются данные",
          "yes": "Да"
        },
      };
}
